services:
  api:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgresql://forecast_user:forecast_pass@postgres:5432/forecast_db

  postgres:
    image: postgres:16
    environment:
      - POSTGRES_USER=forecast_user
      - POSTGRES_PASSWORD=forecast_pass
      - POSTGRES_DB=forecast_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  mlflow:
    image: ghcr.io/mlflow/mlflow:latest
    ports:
      - "5001:5000"
    volumes:
      - mlflow_data:/mlflow
    command: >
      mlflow server
      --backend-store-uri sqlite:///mlflow/mlflow.db
      --artifacts-destination /mlflow/artifacts
      --serve-artifacts
      --host 0.0.0.0
      --port 5000

volumes:
  pgdata:
  mlflow_data: 